package app.model;

public interface CodigoError {
    int SIN_ERROR = 0;
    int ERROR_SIN_CONEXION = 1;
    int ERROR_USUARIO_YA_EXISTE = 2;
    int ERROR_USUARIO_NO_REGISTRADO = 3;
    int ERROR_USUARIO_PASSWORD_INCORRECTA = 4;
    int ERROR_USUARIO_NOMBRE_CORTO = 5;
    int ERROR_USUARIO_NOMBRE_LARGO = 6;
    int ERROR_USUARIO_PASSWORD_CORTA = 7;
    int ERROR_USUARIO_PASSWORD_LARGA = 8;
    int ERROR_USUARIO_PASSWORD_CON_ESPACIOS = 9;
    int ERROR_USUARIO_PASSWORD_CARACTERES_RAROS = 10;
    int ERROR_TAREA_SIN_NOMBRE = 11;
    int ERROR_TAREA_NOMBRE_EN_BLANCO = 12;
    int ERROR_TAREA_NOMBRE_LARGO = 13;
    int ERROR_TAREA_SIN_CAMBIOS = 14;
}
